include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = vis0g3Prefs

vis0g3Prefs_FILES = \
	VZRootListController.mm \
	VZFaceListController.mm

vis0g3Prefs_INSTALL_PATH    = /Library/PreferenceBundles
vis0g3Prefs_FRAMEWORKS      = UIKit Foundation
vis0g3Prefs_PRIVATE_FRAMEWORKS = Preferences
vis0g3Prefs_CFLAGS          = -fobjc-arc
vis0g3Prefs_CCFLAGS         = -fobjc-arc -std=c++17

include $(THEOS_MAKE_PATH)/bundle.mk
